# Generated by Django 4.2.15 on 2024-08-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="encoding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
