# Generated by Django 4.2.15 on 2024-08-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0002_userprofile_encoding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recognizedface",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="recognized_faces/"
            ),
        ),
    ]
